
2023-02-08 22:38:46 NO_MSG
Here is the error good luck solving it :)
Traceback (most recent call last):
  File "/Users/tassosmakro/PyProjects/PyTerminal/launcher.py", line 29, in boot
    _run()
  File "/Users/tassosmakro/PyProjects/PyTerminal/launcher.py", line 10, in _run
    kernel.core(MODE=flags.MODE)
  File "/Users/tassosmakro/PyProjects/PyTerminal/ModeHandling.py", line 15, in core
    IO.CommandAsk(MD=MODE, Module=cmd.CommandList)
  File "/Users/tassosmakro/PyProjects/PyTerminal/Kernel/Input_Output.py", line 18, in CommandAsk
    Module(Command=input(f"{flags.MD9} | {flags.sys_detect.system} | {flags.sys_detect.machine} % ").lower(), cmd_pl=flags.pl, MD=flags.MODE)
  File "/Users/tassosmakro/PyProjects/PyTerminal/commands.py", line 314, in CommandList
    os.startfile('test.py')
AttributeError: module 'os' has no attribute 'startfile'
